allowBuilds:
  '@ampproject/toolbox-optimizer': true
  '@prisma/engines': true
  es5-ext: true
  fsevents: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@prisma/client-runtime-utils@7.9.1'
  - '@prisma/client@7.9.1'
  - '@prisma/config@7.9.1'
  - '@prisma/debug@7.9.1'
  - '@prisma/dev@0.24.17'
  - '@prisma/engines@7.9.1'
  - '@prisma/fetch-engine@7.9.1'
  - '@prisma/get-platform@7.9.1'
  - prisma@7.9.1
overrides:
  "sharp": "0.35.3"
  "postcss": "8.5.23"